name: Check Libraries, Update Requirements, and Run Script

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Replace with the Python version your project needs

    - name: Install Existing Dependencies
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          touch requirements.txt
        fi

    - name: Check and Update Missing Libraries
      run: |
        # Extract imports from leo.py
        grep "^import " leo.py > imports.txt || true
        grep "^from " leo.py >> imports.txt || true

        # Initialize a flag for missing libraries
        missing_libs="false"

        # Check for missing libraries
        while IFS= read -r line; do
          lib=$(echo "$line" | awk '{print $2}' | cut -d. -f1)
          if ! pip show "$lib" > /dev/null 2>&1; then
            echo "Missing library detected: $lib"
            # Append the missing library to requirements.txt if not already present
            if ! grep -q "^$lib" requirements.txt; then
              echo "$lib" >> requirements.txt
              echo "$lib added to requirements.txt"
              missing_libs="true"
            fi
          fi
        done < imports.txt

        if [ "$missing_libs" = "true" ]; then
          echo "New libraries added to requirements.txt. Please review and push changes."
          exit 1
        fi

    - name: Run Script
      run: python leo.py
